import { getDefaultMock } from '../default/default.msw';

/**
 * MSW request handlers generated by orval from the OpenAPI spec.
 * Responses are driven by the spec `example` values (deterministic),
 * not faker-randomised data.
 */
export const handlers = [...getDefaultMock()];
