/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Todo API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  Todo
} from '../todoAPI.schemas';


export const getGetTodosResponseMock = (): Todo[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.float({fractionDigits: 2}), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean()})))

export const getPostTodosResponseMock = (overrideResponse: Partial<Extract<Todo, object>> = {}): Todo => ({id: faker.number.float({fractionDigits: 2}), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean(), ...overrideResponse})

export const getGetTodosIdResponseMock = (overrideResponse: Partial<Extract<Todo, object>> = {}): Todo => ({id: faker.number.float({fractionDigits: 2}), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean(), ...overrideResponse})

export const getPatchTodosIdResponseMock = (overrideResponse: Partial<Extract<Todo, object>> = {}): Todo => ({id: faker.number.float({fractionDigits: 2}), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean(), ...overrideResponse})

