import { setupWorker } from 'msw/browser';

import { getDefaultMock } from '../default/default.msw';

/**
 * MSW worker for the browser runtime.
 * Start it during app bootstrap (e.g. behind a dev flag) with `worker.start()`.
 * Requires the service worker script generated by `npx msw init public --save`.
 */
export const worker = setupWorker(...getDefaultMock());
