import { setupServer } from 'msw/node';

import { getDefaultMock } from '../default/default.msw';

/**
 * MSW server for Node-based environments (Vitest / SSR).
 * Handlers are generated by orval from the OpenAPI spec.
 */
export const server = setupServer(...getDefaultMock());
