/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Todo API
 * OpenAPI spec version: 1.0.0
 */
export interface Todo {
  id: number;
  title: string;
  done: boolean;
}

export interface NotFound {
  message: string;
}

export interface CreateTodo {
  title: string;
}

